In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#import chaospy as cp
import numpy as np 
from scipy.stats import norm

import matplotlib.pyplot as plt
%matplotlib inline

import sys
sys.path.append("..")
from src.py.option import AsianOption
from src.py.tasmanian_tools import make_grid

In [3]:
s_0_l=80.0
s_0_r=120.0
sigma_l=0.1
sigma_r=0.2
mu_l=0.02
mu_r=0.05
T_l=0.9
T_r=1.0
K_l=109.0
K_r=110.0

In [16]:
# max possible dim, level before 16 GB RAM is full: 40, 4
%time
dim = 16
aop = AsianOption(d=dim)
level = 4
lb, rb = np.zeros(dim), np.ones(dim)

grid = make_grid(dim, level, lb, rb, "gauss-patterson")
weights, points = grid.getQuadratureWeights(), grid.getPoints()
pre_factor = np.exp(-aop.r*aop.T+aop.M)
payout_v = aop.payout_func_opt(points)
pre_factor*np.inner(weights, payout_v), aop.scholes_call()

CPU times: user 1e+03 ns, sys: 1 µs, total: 2 µs
Wall time: 3.34 µs


(7.152087238522643, 7.15590176686306)

In [12]:
s_0 = np.linspace(s_0_l, s_0_r, 21)
sigma = np.linspace(sigma_l, sigma_r, 5)
mu = np.linspace(mu_l, mu_r, 9)
T = np.linspace(T_l, T_r, 9)
K = np.linspace(K_l, K_r, 9)
s_0, sigma, mu, T, K

(array([ 80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,  98., 100.,
        102., 104., 106., 108., 110., 112., 114., 116., 118., 120.]),
 array([0.1  , 0.125, 0.15 , 0.175, 0.2  ]),
 array([0.02   , 0.02375, 0.0275 , 0.03125, 0.035  , 0.03875, 0.0425 ,
        0.04625, 0.05   ]),
 array([0.9   , 0.9125, 0.925 , 0.9375, 0.95  , 0.9625, 0.975 , 0.9875,
        1.    ]),
 array([109.   , 109.125, 109.25 , 109.375, 109.5  , 109.625, 109.75 ,
        109.875, 110.   ]))